### ISSUE TITLE
Time between fragments

### ISSUE THREAD

**Issue by EnzChe** [ahmedrizwan/ChronometerPersist#1]
Hello,

I got an app with your ChronometerPersist. On the main fragment I got a list of Timers and users can play, pause, stop.
But when I change fragment and go back to the "TimerFragment" all are reseted to 00:00. I need to keep them running if they are running or keep their value if they are paused.

Thanks !

**Comment by ahmedrizwan** [comment]
Yes on fragment's onResume, call the method `chronometerPersist.resumeState();` so that the state is recovered. Let me know if it works for you. Thanks!

**Comment by EnzChe** [comment]
Ok thanks I will try.
And another question and I got a list of timers with checkboxes and a button to pause/start all checked timers. This is my button "Pause" code :

```
public void onClick(View v) {
  for (Timer t : mainActivity.timerList) {
    if (t.isChecked()) {
      if (t.getChrono().isRunning()) {
        Log.d("___________", "Timer checked running : " + t.toString());
        t.getChrono().pauseChronometer();
      } else {
        Log.d("___________", "Timer checked paused : " + t.toString());
        t.getChrono().startChronometer();
      }
    }
  }
}
```

But the problem is when I call 't.getChrono().pauseChronometer();' all followed chrono on the for loop are set to pause.

EDIT :
The resumeState is only resuming the first chronometer of my ArrayList with the last Chronometer paused value
