### ISSUE TITLE
Wrong chronometer state

### ISSUE THREAD

**Issue by AlexMisha** [ahmedrizwan/ChronometerPersist#2]
Hello, here are steps to reproduce a bug:

1. Call startChronometer().
2. Wait for 5 seconds to pass.
3. Call stopChronometer().
4. Call startChronometer().
5. Call startChronometer().
Then chronometer would show 5 seconds instead of 0 second expected.

Devices:
LG Bello D335, android 5.0
Redmi 4X, android 7.1 (emulator)

Thanks.

**Comment by ahmedrizwan** [comment]
Please update to v1.2.0 - this issue shouldn't popup. If it does, you can re-open this issue. Thanks!
