### ISSUE TITLE
Chronometer time reverses after device restarts

### ISSUE THREAD

**Issue by bryan-ibrahim** [ahmedrizwan/ChronometerPersist#3]
I noticed after the restarting my device, the chronometer would decrease in time instead of continuing.

**Comment by stillie** [comment]
I have this same issue with the base Chronometer and its something i cannot for the life of me figure out.... i was hoping this library would've fixed that or at least hinted at a solution

**Comment by ahmedrizwan** [comment]
@stillie @bryan-ibrahim apologies for the super-late response. I'll fix this issue over this weekend. It's been a long time since I worked on this project, so I'll go through it and will make sure it integrates properly. Thanks!

**Comment by ahmedrizwan** [comment]
@stillie @bryan-ibrahim I've published version 1.2.0 with fixes. Please update and use that version, thanks!
